routes/web.php
<?php


Route::get('/', function () {
    return view('home');
});

/*Haciendo un grupo de rutas... para el Director*/
Route::group(['prefix' => 'director', 'namespace' => 'Director', 'as' =>'director.', 'middleware' => ['auth','director']], function(){
	//Grupo de rutas para el Director/Curso
	Route::group(['prefix' => 'curso', 'as' =>'curso.'], function(){
		Route::get('/', [
			'uses' => 'CursoController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'CursoController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'CursoController@store',
			'as' => 'store']);
		Route::get('{curso}',[
			'uses' => 'CursoController@show',
			'as' => 'show']);
		Route::get('{curso}/edit',[
			'uses' => 'CursoController@edit',
			'as' => 'edit']);
		Route::put('{curso}',[
			'uses' => 'CursoController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'CursoController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Director/Docente
	Route::group(['prefix' => 'docente', 'as' =>'docente.'], function(){
		Route::get('/', [
			'uses' => 'DocenteController@index',
			'as' => 'index']);
		Route::post('/',[
			'uses' => 'DocenteController@store',
			'as' => 'store']);
		Route::get('{docente}',[
			'uses' => 'DocenteController@show',
			'as' => 'show']);
		Route::get('{docente}/edit',[
			'uses' => 'DocenteController@edit',
			'as' => 'edit']);
		Route::put('{docente}',[
			'uses' => 'DocenteController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'DocenteController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Director/Semestre
	Route::group(['prefix' => 'semestre', 'as' =>'semestre.'], function(){
		Route::get('/', [
			'uses' => 'SemestreController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'SemestreController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'SemestreController@store',
			'as' => 'store']);
		Route::post('storeCurso',[
			'uses' => 'SemestreController@storeCurso',
			'as' => 'storeCurso']);
		Route::post('storeCursoDocente',[
			'uses' => 'SemestreController@storeCursoDocente',
			'as' => 'storeCursoDocente']);
		Route::get('{semestre}',[
			'uses' => 'SemestreController@show',
			'as' => 'show']);
		Route::get('{semestre}/edit',[
			'uses' => 'SemestreController@edit',
			'as' => 'edit']);
		Route::put('{semestre}',[
			'uses' => 'SemestreController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'SemestreController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Director/silabo

	Route::group(['prefix' => 'silabo', 'as' =>'silabo.'], function(){
		Route::get('/', [
			'uses' => 'SilaboController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'SilaboController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'SilaboController@store',
			'as' => 'store']);
		Route::get('{silabo}',[
			'uses' => 'SilaboController@show',
			'as' => 'show']);
		Route::get('{silabo}/edit',[
			'uses' => 'SilaboController@edit',
			'as' => 'edit']);
		Route::put('{silabo}',[
			'uses' => 'SilaboController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'SilaboController@destroy',
			'as' => 'destroy']);
		Route::get('{silabo}',[
			'uses' => 'SilaboController@temaIndex',
			'as' => 'temaIndex']);
	});

	//Route::resource('silabo', 'SilaboController');


});


/*Haciendo un grupo de rutas... para el Docente*/
Route::group(['prefix' => 'docente', 'namespace' => 'Docente', 'as' =>'docente.', 'middleware' => ['auth','docente']], function(){
	//Grupo de rutas para el Docente/curso
	Route::group(['prefix' => 'curso', 'as' =>'curso.'], function(){
		Route::get('/', [
			'uses' => 'CursoController@index',
			'as' => 'index']);
		Route::post('create', [
			'uses' => 'CursoController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'CursoController@store',
			'as' => 'store']);
		Route::get('{curso}',[
			'uses' => 'CursoController@show',
			'as' => 'show']);
		Route::get('{curso}/edit',[
			'uses' => 'CursoController@edit',
			'as' => 'edit']);
		Route::put('{curso}',[
			'uses' => 'CursoController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'CursoController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Docente/temas
	Route::group(['prefix' => 'tema', 'as' =>'tema.'], function(){
		Route::get('/', [
			'uses' => 'TemaController@index',
			'as' => 'index']);
		Route::post('/',[
			'uses' => 'TemaController@store',
			'as' => 'store']);
		Route::get('{tema}',[
			'uses' => 'TemaController@show',
			'as' => 'show']);
		Route::get('{tema}/edit',[
			'uses' => 'TemaController@edit',
			'as' => 'edit']);
		Route::put('{tema}',[
			'uses' => 'TemaController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'TemaController@destroy',
			'as' => 'destroy']);
	});	
});

/*Haciendo un grupo de rutas... para el Delegado*/
Route::group(['prefix' => 'delegado', 'namespace' => 'Delegado', 'as' =>'delegado.', 'middleware' => ['auth','delegado']], function(){
	//Grupo de rutas para el Delegado/cursos
	Route::group(['prefix' => 'curso', 'as' =>'curso.'], function(){
		Route::get('/', [
			'uses' => 'CursoController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'CursoController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'CursoController@store',
			'as' => 'store']);
		Route::get('{curso}',[
			'uses' => 'CursoController@show',
			'as' => 'show']);
		Route::get('{curso}/edit',[
			'uses' => 'CursoController@edit',
			'as' => 'edit']);
		Route::put('{curso}',[
			'uses' => 'CursoController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'CursoController@destroy',
			'as' => 'destroy']);
	});
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'perfil', 'as' => 'perfil.', 'middleware' => 'auth'], function(){
	Route::get('/', [
		'uses' => 'PersonaController@index',
		'as' => 'index']);
	Route::get('create', [
		'uses' => 'PersonaController@create',
		'as' => 'create']);
	Route::post('/',[
		'uses' => 'PersonaController@store',
		'as' => 'store']);
	Route::get('{semestre}',[
		'uses' => 'PersonaController@show',
		'as' => 'show']);
	Route::get('{semestre}/edit',[
		'uses' => 'PersonaController@edit',
		'as' => 'edit']);
	Route::put('{semestre}',[
		'uses' => 'PersonaController@update',
		'as' => 'update']);
	Route::get('{id}/destroy',[
		'uses' => 'PersonaController@destroy',
		'as' => 'destroy']);
});

app/Http/Controllers/Delegado/CursoController.php
<?php

namespace CSilabo\Http\Controllers\Delegado;

use Illuminate\Http\Request;
use CSilabo\Http\Controllers\Controller;

class CursoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('delegado.curso.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Director/CursoController.php
<?php

namespace CSilabo\Http\Controllers\Director;

use Illuminate\Http\Request;
use CSilabo\Http\Controllers\Controller;

use CSilabo\Model\Curso;
use CSilabo\Model\curso_requisito;
use CSilabo\Model\Sumilla;
use Validator;
use DB;
class CursoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$cursos = Curso::all()->select('id','codigo','nombre')->orderBy('codigo','ASC')->get();
        $cursos=DB::table('cursos')
            ->select('id','codigo','nombre')
            ->orderBy('codigo','ASC')
            ->get();
        //dd($cursos);
        return view('director.curso.index', compact('cursos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cursos = Curso::orderBy('id','DESC')->get();
        return view('director.curso.create', compact('cursos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nombre' => 'required|min:2|max:100|unique:cursos',
            'codigo' => 'required|min:10|max:10|unique:cursos',
            /*'creditos' => 'required|min:2|max:100',
            'codigo' => 'required|numeric|min:10|max:10',
            'creditos' => 'required|numeric|min:10|max:10',*/
        ]);

        if($validator->fails()){
            flash('Informacion ya exitente')->error();
            return redirect()->route('director.curso.index')
                        ->withErrors($validator)
                        ->withInput();
        }
        $curso=new Curso($request->all());
        $curso->save();
        $sumilla=new sumilla();
        $sumilla->descripcion=$request->sumilla;
        $sumilla->estado='vigente';
        $sumilla->fecha=date('Y-m-d');
        $sumilla->curso_id=$curso->id;
        $sumilla->save();

        //$curso->curso_requisito()->sync($request->curso_requisito);
        if ($request->curso_requisito!=null) {
            foreach ($request->curso_requisito as $c_requisito) {
                $curso_requisito= new curso_requisito();
                $curso_requisito->curso_id=$curso->id;
                $curso_requisito->curso_requisito_id=$c_requisito;
                $curso_requisito->save();
            }
        }
        

        flash('Registrado correctamente')->success();
        return redirect()->route('director.curso.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $curso=Curso::find($id);
        $curso->delete();
        flash('Curso '.$curso->nombre.' Eliminado')->error();
        return redirect()->route('director.curso.index');
    }
}

app/Http/Controllers/Director/DocenteController.php
<?php

namespace CSilabo\Http\Controllers\Director;

use Illuminate\Http\Request;
use CSilabo\Http\Controllers\Controller;

use CSilabo\Model\Persona;
use CSilabo\Model\Role;
use DB;
use Validator;
class DocenteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $docentes = DB::table('personas')
            ->join('persona_role', 'persona_role.persona_id', '=', 'personas.id')
            ->select('personas.*')
            ->where('persona_role.role_id', '=', 1)
            ->orderBy('paterno', 'ASC')
            ->get();
        return view('director.docente.index',compact('docentes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nombre' => 'required|min:2|max:100',
            'paterno' => 'required|min:2|max:100',
            'materno' => 'max:100',
            'email' => 'email|required|unique:personas',
            'codigo' => 'nullable|unique:personas',
            'password' => 'required|min:4|max:255',
        ]);
        if($validator->fails()){
            return redirect()->route('director.docente.index')
                        ->withErrors($validator)
                        ->withInput();
        }
        $persona=new Persona($request->all());
        //$user->fill($request->all());
        $persona->password=bcrypt($request->password);
        $persona->save();

        $role=Role::where('nombre','Docente')->select('id')->get();

        $persona->roles()->sync($role);
        flash('Registrado correctamente')->success();
        return redirect()->route('director.docente.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $docente = Persona::find($id);
        return view('director.docente.show', compact('docente'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $docente = Persona::find($id);
        return view('director.docente.edit', compact('docente'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'nombre' => 'required|min:2|max:100',
            'paterno' => 'required|min:2|max:100',
            'materno' => 'required|min:2|max:100',
            'codigo' => 'nullable|unique:personas',
            'email' => 'email|required',
            'password' => 'required|min:4|max:255',
        ]);
        //dd($request->email);
        $var = DB::table('personas')
                ->where('personas.email','=',$request->email)
                ->where('personas.id','<>',$id)
                ->count();
        //dd($var);
        if($var){
            $validator->errors()->add('field', 'Email registrado a otra persona');
            flash('Email existente');
        }

        if($validator->fails() || $var){
            return redirect()->route('director.docente.index')
                        ->withErrors($validator)
                        ->withInput();
        }
        $docente=Persona::find($id);
        $docente->fill($request->all());
        $docente->password=bcrypt($request->password);
        $docente->save();
        flash('Modificado Correctamente')->success();
        return redirect()->route('director.docente.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $docente=Persona::find($id);
        $docente->delete();
        flash('Docente '.$docente->nombre.' Eliminado')->error();
        return redirect()->route('director.docente.index');
    }
}

resources/views/docente/curso/create.blade.php
@extends('template.main')

@section('title-body','Creación de silabo: '.$curso->nombre)
@section('content')
<ul class="stepper horizontal">
   <li class="step active">
      <div class="step-title waves-effect"></div>
      <div class="step-content">
         <div class="row">
          <h5>I. INFORMACIÓN GENERAL</h5>
          <!--             
            <div class="input-field col s12">
               <input id="email" name="email" type="email" class="validate" required>
               <label for="first_name">Your e-mail</label>
            </div>
           -->

            <div class="col s12">
                <div class="col s12 l4">
                    <p class="">1.1 Área</p>
                </div>
                <div class="col s11 l8 offset-s1">
                    <input type="text" name="" id="area" class="validate" required value="{{ $curso->area }}" disabled>
                </div>
            </div>

            <div class="col s12">
                <div class="col s6 l4">
                    <p class="">1.2 Código</p>
                </div>
                <div class="col s6 l8">
                    <input type="text" name="" id="" class="validate" required value="{{ $curso->codigo }}" disabled>
                </div>
            </div>

            <div class="col s12">
                <div class="col s6 l4">
                    <p class="">1.3 Ciclo</p>
                </div>
                <div class="col s6 l8">
                    <input type="text" name="" id="" class="validate" required value="{{ $curso->ciclo }}" disabled>
                </div>
            </div>

            <div class="col s12">
                <div class="col s6 l4">
                    <p class="">1.4 Créditos</p>
                </div>
                <div class="col s6 l8">
                    <input type="text" name="" id="" class="validate" required value="{{ $curso->creditos }}" disabled>
                </div>
            </div>

            <div class="col s12">
                <div class="col s6 l4">
                    <p class="">1.5 Semestre Académico</p>
                </div>
                <div class="col s6 l8">
                    <input type="text" name="" id="" class="validate" required value="{{ $semestre->nombre }}" disabled>
                </div>
            </div>

            <div class="col s12">
                <div class="col s6 l4">
                    <p class="">1.6 Duración</p>
                </div>
                <div class="col s6 l8">
                    <input type="text" name="" id="" class="validate" placeholder="Duración del semestre en semanas">
                </div>
            </div>

            <div class="col s12">
                <div class="col s6 l4">
                    <p class="">1.7 Horas de Contacto Semanal</p>
                </div>
                <div class="col s6 l8">
                    <input type="text" name="" id="" class="validate" placeholder="Numero de horas totales de clases a la semana">
                </div>
            </div>

            <div class="col s12">
                <div class="col s5 l3 offset-s1 offset-l1">
                    <p class="">1.7.1 Horas de teoría</p>
                </div>
                <div class="col s6 l8">
                    <input type="text" name="" id="" class="validate" placeholder="Horas de sesiones teoricas a la semana">
                </div>
            </div>

            <div class="col s12">
                <div class="col s5 l3 offset-s1 offset-l1">
                    <p class="">1.7.2 Horas de práctica</p>
                </div>
                <div class="col s6 l8">
                    <input type="text" name="" id="" class="validate" placeholder="Horas de sesiones prácticas a la semana">
                </div>
            </div>

            <div class="col s12">
                <div class="col s6 l4">
                    <p class="">1.8 Horas de Trabajo Independiente</p>
                </div>
                <div class="col s6 l8">
                    <input type="text" name="" id="" class="validate" placeholder="Horas a la semana que el estudiante debe dedicar al curso fuera de clases">
                </div>
            </div>

            <div class="col s12">
                <div class="col s12 l4">
                    <p class="">1.9 Requisito(s)</p>
                </div>
                <div class="col s12 l8">
                    <input type="text" name="" id="" class="validate" placeholder="Cursos requisitos para el curso">
                </div>
            </div>

            <div class="col s12">
                <div class="col s12 l4">
                    <p class="">1.10 Escuela Profesional</p>
                </div>
                <div class="col s11 l8 offset-s1">
                    <input type="text" name="" id="" class="validate" placeholder="Escuela profesional">
                </div>
            </div>

            <div class="col s12">
                <div class="col s12 l4">
                    <p class="">1.11 Docente</p>
                </div>
                <div class="col s11 l8 offset-s1">
                    <input type="text" name="" id="" class="validate" placeholder="Docente del curso">
                </div>
            </div>

            <div class="col s12">
                <div class="col s12 l4">
                    <p class="">1.12 Texto Basico</p>
                </div>
                <div class="col s11 l8 offset-s1">
                    <input type="text" name="" id="" class="validate" placeholder="Texto de referencia al curso">
                </div>
            </div>

            <div class="col s12">
                <div class="col s12 l4">
                    <p>1.13 Numero Maximo de Estudiantes</p>
                </div>              
                <div class="col s11 l8 offset-s1">
                        <div class="input-field inline col s6">
                            <input type="text" name="" id="" class="validate">              
                            <label>En sesiones Teoricas</label>
                        </div>
                        <div class="input-field inline col s6">
                            <input type="text" name="" id="" class="validate">
                            <label>En sesiones Prácticas</label>
                        </div>
                </div>
            </div>
         </div>
         <div class="step-actions">
            <button class="waves-effect waves-dark btn next-step">CONTINUE</button>
         </div>
      </div>
   </li>
   <li class="step">
      <div class="step-title waves-effect"></div>
      <div class="step-content">
         <div class="row">
          <h5>II. SUMILLA</h5>
            <div class="input-field col s12">
               <input id="password" name="password" type="password" class="validate" required>
               <label for="password">Your password</label>
            </div>
         </div>
         <div class="step-actions">
            <button class="waves-effect waves-dark btn next-step">CONTINUE</button>
            <button class="waves-effect waves-dark btn-flat previous-step">BACK</button>
         </div>
      </div>
   </li>
   <li class="step">
      <div class="step-title waves-effect"></div>
      <div class="step-content">
         <div class="row">
          <h5>III. COMPETENCIAS</h5>
            <div class="input-field col s12">
               <input id="password2" name="password2" type="password" class="validate" required>
               <label for="password2">Your password2</label>
            </div>
         </div>
         <div class="step-actions">
            <button class="waves-effect waves-dark btn next-step">CONTINUE</button>
            <button class="waves-effect waves-dark btn-flat previous-step">BACK</button>
         </div>
      </div>
   </li>
   <li class="step">
      <div class="step-title waves-effect"></div>
      <div class="step-content">
         <div class="row">
          <h5>IV. PROGRAMACIÓN DE CONTENIDOS</h5>
            <div class="input-field col s12">
               <input id="password3" name="password3" type="password" class="validate" required>
               <label for="password3">Your password3</label>
            </div>
         </div>
         <div class="step-actions">
            <button class="waves-effect waves-dark btn next-step">CONTINUE</button>
            <button class="waves-effect waves-dark btn-flat previous-step">BACK</button>
         </div>
      </div>
   </li>
   <li class="step">
      <div class="step-title waves-effect"></div>
      <div class="step-content">
         <div class="row">
          <h5>V. PROCEDIMIENTOS DIDÁCTICOS</h5>
            <div class="input-field col s12">
               <input id="password4" name="password4" type="password" class="validate" required>
               <label for="password4">Your password4</label>
            </div>
         </div>
         <div class="step-actions">
            <button class="waves-effect waves-dark btn next-step">CONTINUE</button>
            <button class="waves-effect waves-dark btn-flat previous-step">BACK</button>
         </div>
      </div>
   </li>
   <li class="step">
      <div class="step-title waves-effect"></div>
      <div class="step-content">
         <div class="row">
          <h5>VI. VIAJE DE PRACTICAS (VISITAS TÉCNICAS)</h5>
            <div class="input-field col s12">
               <input id="password5" name="password5" type="password" class="validate" required>
               <label for="password5">Your password5</label>
            </div>
         </div>
         <div class="step-actions">
            <button class="waves-effect waves-dark btn next-step">CONTINUE</button>
            <button class="waves-effect waves-dark btn-flat previous-step">BACK</button>
         </div>
      </div>
   </li>
   <li class="step">
      <div class="step-title waves-effect"></div>
      <div class="step-content">
         <div class="row">
          <h5>VII. MEDIOS Y MATERIALES EDUCATIVOS</h5>
            <div class="input-field col s12">
               <input id="password6" name="password6" type="password" class="validate" required>
               <label for="password6">Your password6</label>
            </div>
         </div>
         <div class="step-actions">
            <button class="waves-effect waves-dark btn next-step">CONTINUE</button>
            <button class="waves-effect waves-dark btn-flat previous-step">BACK</button>
         </div>
      </div>
   </li>
   <li class="step">
      <div class="step-title waves-effect"></div>
      <div class="step-content">
         <div class="row">
          <h5>VIII. EVALUACIÓN</h5>
            <div class="input-field col s12">
               <input id="password7" name="password7" type="password" class="validate" required>
               <label for="password7">Your password7</label>
            </div>
         </div>
         <div class="step-actions">
            <button class="waves-effect waves-dark btn next-step">CONTINUE</button>
            <button class="waves-effect waves-dark btn-flat previous-step">BACK</button>
         </div>
      </div>
   </li>
   <li class="step">
      <div class="step-title waves-effect"></div>
      <div class="step-content">
        <div class="row">
          <h5>IX. BIBLIOGRAFÍA</h5>
        </div>
         <div class="step-actions">
            <button class="waves-effect waves-dark btn" type="submit">SUBMIT</button>
         </div>
      </div>
   </li>
</ul>
@endsection
@section('js')
<script type="text/javascript">
  $(function(){
    $('.stepper').activateStepper();
  });
</script>
@endsection

resources/views/docente/curso/index.blade.php
@extends('template.main')

@section('title-body','Mis Cursos')
@section('content')
<div class="row">
  <div class="col s12 m9 nav nav-wrapper">
      <form>
        <div class="input-field col s8">
          <input id="search" type="search" required class="validate" placeholder="[Buscar]">
        </div>

        <div class="col s2 right-align">
            <a class="btn-floating waves-effect waves-light blue darken-4"><i class="material-icons">search</i></a>
        </div>
      </form>

      <div class="col s2">
          <a class="btn-floating waves-effect waves-light green darken-4" href="{{ route('director.silabo.index') }}"><i class="material-icons">update</i></a>
      </div>
  </div>

      <table class="highlight responsive-table">
        <thead>
          <tr>
              <th>Curso</th>
              <th>Codigo</th>
              <th>Semestre</th>
              <th>Opciones del Silabo</th>
          </tr>
        </thead>

        <tbody>
         @foreach($cursos as $curso)
          <tr>
            <td>{{ $curso->curso_nombre }}</td>
            <td>{{ $curso->curso_codigo }}</td>
            <td>{{ $curso->semestre }}</td>
            <td class="row">
              <a class="none waves-effect waves-light right-align"
                onclick="event.preventDefault();
                document.getElementById('silaboAddForm').submit();">
                <i class="material-icons" style="color:#f57c00 ;">note_add</i>
              </a>
              <form id="silaboAddForm" action="{{ route('docente.curso.create') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
                <input type="hidden" name="semestre_id" value="{{ $curso->semestre_id }}">
                <input type="hidden" name="curso_id" value="{{ $curso->curso_id }}">
              </form>
              <a class="none waves-effect waves-light right-align"><i class="material-icons" style="color: rgba(5, 100, 24, 1);">edit</i></a>
              <a class="none waves-effect waves-light right-align"><i class="material-icons" style="color: rgba(250, 0, 0, 1);">delete</i></a>
              <a class="none waves-effect waves-light right-align"><i class="material-icons" style="color: rgba(13,71,171, 1);">remove_red_eye</i></a>
            </td>
          </tr>
         @endforeach
       </tbody>
      </table>
</div>
@endsection