routes/web.php
<?php


Route::get('/', function () {
    return view('home');
});

/*Haciendo un grupo de rutas... para el Director*/
Route::group(['prefix' => 'director', 'namespace' => 'Director', 'as' =>'director.', 'middleware' => ['auth','director']], function(){
	//Grupo de rutas para el Director/Curso
	Route::group(['prefix' => 'curso', 'as' =>'curso.'], function(){
		Route::get('/', [
			'uses' => 'CursoController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'CursoController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'CursoController@store',
			'as' => 'store']);
		Route::get('{curso}',[
			'uses' => 'CursoController@show',
			'as' => 'show']);
		Route::get('{curso}/edit',[
			'uses' => 'CursoController@edit',
			'as' => 'edit']);
		Route::put('{curso}',[
			'uses' => 'CursoController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'CursoController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Director/Docente
	Route::group(['prefix' => 'docente', 'as' =>'docente.'], function(){
		Route::get('/', [
			'uses' => 'DocenteController@index',
			'as' => 'index']);
		Route::post('/',[
			'uses' => 'DocenteController@store',
			'as' => 'store']);
		Route::get('{docente}',[
			'uses' => 'DocenteController@show',
			'as' => 'show']);
		Route::get('{docente}/edit',[
			'uses' => 'DocenteController@edit',
			'as' => 'edit']);
		Route::put('{docente}',[
			'uses' => 'DocenteController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'DocenteController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Director/Semestre
	Route::group(['prefix' => 'semestre', 'as' =>'semestre.'], function(){
		Route::get('/', [
			'uses' => 'SemestreController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'SemestreController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'SemestreController@store',
			'as' => 'store']);
		Route::post('storeCurso',[
			'uses' => 'SemestreController@storeCurso',
			'as' => 'storeCurso']);
		Route::post('storeCursoDocente',[
			'uses' => 'SemestreController@storeCursoDocente',
			'as' => 'storeCursoDocente']);
		Route::get('{semestre}',[
			'uses' => 'SemestreController@show',
			'as' => 'show']);
		Route::get('{semestre}/edit',[
			'uses' => 'SemestreController@edit',
			'as' => 'edit']);
		Route::put('{semestre}',[
			'uses' => 'SemestreController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'SemestreController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Director/silabo

	Route::group(['prefix' => 'silabo', 'as' =>'silabo.'], function(){
		Route::get('/', [
			'uses' => 'SilaboController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'SilaboController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'SilaboController@store',
			'as' => 'store']);
		Route::get('{silabo}',[
			'uses' => 'SilaboController@show',
			'as' => 'show']);
		Route::get('{silabo}/edit',[
			'uses' => 'SilaboController@edit',
			'as' => 'edit']);
		Route::put('{silabo}',[
			'uses' => 'SilaboController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'SilaboController@destroy',
			'as' => 'destroy']);
		Route::get('{silabo}',[
			'uses' => 'SilaboController@temaIndex',
			'as' => 'temaIndex']);
	});

	//Route::resource('silabo', 'SilaboController');


});


/*Haciendo un grupo de rutas... para el Docente*/
Route::group(['prefix' => 'docente', 'namespace' => 'Docente', 'as' =>'docente.', 'middleware' => ['auth','docente']], function(){
	//Grupo de rutas para el Docente/curso
	Route::group(['prefix' => 'curso', 'as' =>'curso.'], function(){
		Route::get('/', [
			'uses' => 'CursoController@index',
			'as' => 'index']);
		Route::post('create', [
			'uses' => 'CursoController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'CursoController@store',
			'as' => 'store']);
		Route::get('{curso}',[
			'uses' => 'CursoController@show',
			'as' => 'show']);
		Route::get('{curso}/edit',[
			'uses' => 'CursoController@edit',
			'as' => 'edit']);
		Route::put('{curso}',[
			'uses' => 'CursoController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'CursoController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Docente/temas
	Route::group(['prefix' => 'tema', 'as' =>'tema.'], function(){
		Route::get('/', [
			'uses' => 'TemaController@index',
			'as' => 'index']);
		Route::post('/',[
			'uses' => 'TemaController@store',
			'as' => 'store']);
		Route::get('{tema}',[
			'uses' => 'TemaController@show',
			'as' => 'show']);
		Route::get('{tema}/edit',[
			'uses' => 'TemaController@edit',
			'as' => 'edit']);
		Route::put('{tema}',[
			'uses' => 'TemaController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'TemaController@destroy',
			'as' => 'destroy']);
	});	
});

/*Haciendo un grupo de rutas... para el Delegado*/
Route::group(['prefix' => 'delegado', 'namespace' => 'Delegado', 'as' =>'delegado.', 'middleware' => ['auth','delegado']], function(){
	//Grupo de rutas para el Delegado/cursos
	Route::group(['prefix' => 'curso', 'as' =>'curso.'], function(){
		Route::get('/', [
			'uses' => 'CursoController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'CursoController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'CursoController@store',
			'as' => 'store']);
		Route::get('{curso}',[
			'uses' => 'CursoController@show',
			'as' => 'show']);
		Route::get('{curso}/edit',[
			'uses' => 'CursoController@edit',
			'as' => 'edit']);
		Route::put('{curso}',[
			'uses' => 'CursoController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'CursoController@destroy',
			'as' => 'destroy']);
	});
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'perfil', 'as' => 'perfil.', 'middleware' => 'auth'], function(){
	Route::get('/', [
		'uses' => 'PersonaController@index',
		'as' => 'index']);
	Route::get('create', [
		'uses' => 'PersonaController@create',
		'as' => 'create']);
	Route::post('/',[
		'uses' => 'PersonaController@store',
		'as' => 'store']);
	Route::get('{semestre}',[
		'uses' => 'PersonaController@show',
		'as' => 'show']);
	Route::get('{semestre}/edit',[
		'uses' => 'PersonaController@edit',
		'as' => 'edit']);
	Route::put('{semestre}',[
		'uses' => 'PersonaController@update',
		'as' => 'update']);
	Route::get('{id}/destroy',[
		'uses' => 'PersonaController@destroy',
		'as' => 'destroy']);
});

resources/views/template/partials/footer.blade.php
  <div class="page-footer {{ $colorPag }}">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="{{ $textPagT }}">{{ $tema }}</h5>
          <p class="{{ $textPag }}">Proyecto {{ $tema }}</p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="{{ $textPagT }}">Links</h5>
          <ul>
            <li><a class="{{ $textPag }}" href="#!">Privacidad</a></li>
            <li><a class="{{ $textPag }}" href="#!">Condiciones</a></li>
            <li><a class="{{ $textPag }}" href="#!">Cookies</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      <p class="{{ $textPag }}">Aplicacion desarrollada por: <a class="{{ $textPagT }}" href="https://www.facebook.com/elvis.frank.1804" target="_blank"><b>TEAM</b></a>. {{ $tema }} &copy; 2018.</p>
      <a class="{{ $textPagT }} right" href="#!">Mas</a>
      </div>
    </div>
  </div>    

resources/views/template/partials/modal.blade.php
  <!-- Modal Inicio de sesion -->
  <div id="modal-inicio-sesion" class="modal">
    <div class="modal-content">
      <h4>Inicio de Sesion</h4>
      <form>
        <div class="row">
          <div class="input-field col s12">
            <input placeholder="" id="codigo" type="text" class="validate">
            <label for="codigo">Codigo</label>
          </div>
        </div>

        <div class="row">
          <div class="input-field col s12">
            <input placeholder="" id="contraseña" type="password" class="validate">
            <label for="contraseña">Contraseña</label>
          </div>
        </div>
      </form>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-action modal-close waves-effect waves-blue btn-flat">Cancelar</a>
      <a href="#!" class="modal-action modal-close waves-effect waves-blue btn-primary">Iniciar Sesion</a>
    </div>
  </div>

  <!-- Modal Registro de semestre -->
  <div id="semestre-create" class="modal">
    <div class="modal-content">      
      <div class="row">
          <form class="col s12 m10 l8 offset-l2 offset-m1" method="POST" action="{{ route('director.semestre.store') }}">
            {{ csrf_field() }}
            <div class="row center-align"><h4>Registro de Semestre</h4></div>
            <div class="row">
              <div class="col s6 m2 offset-m1">
                <p class="">AÑO</p>
              </div>
              <div class="col s6 m3">
                <input type="text" name="año" id="año" class="validate" placeholder="AÑO">
              </div>
                  <div class="col s6 m2 offset-m1">
                      <p class="">NÚMERO</p>
                  </div>
                  <div class="col s6 m3">
                      <input type="text" name="numero" id="numero" class="validate" placeholder="NÚMERO">
                  </div>
            </div>

              <div class="center-align">
                  <button type="submit" class="waves-effect waves-light btn blue center-align"><i class="material-icons left">save</i>Guardar</button>
              </div>
              <br>
          </form>
        </div>
    </div>
  </div>

  
  <!-- Modal Registro de Docente -->
  <div id="docente-create" class="modal">
    <div class="modal-content">      
      <div class="row">
          <form method="POST" action="{{ route('director.docente.store') }}">
            {{ csrf_field() }}
          <div class="row">

            <h5 class="center-align">DATOS BASICOS PARA ACTIVAR CUENTA</h5>

            <div class="input-field col s12 m8 offset-l1">
              <input type="text" name="nombre" class="validate" minlength="2" maxlength="50" autofocus required>
              <label class="active">Nombre</label>
            </div>

            <div class="input-field col s12 m6 l5 offset-l1">
              <input type="text" name="paterno" class="validate" minlength="2" maxlength="50" required>
              <label>Apellido Paterno</label>
            </div>

            <div class="input-field col s12 m6 l5">
              <input type="text" name="materno" class="validate" minlength="2" maxlength="50">
              <label>Apellido Materno</label>
            </div>

            <div class="input-field col s12 m7 l6 offset-l1">
              <input type="email" name="email" class="validate" minlength="5" maxlength="250" required value="">
              <label>Correo Electrónico</label>
            </div>

            <div class="input-field col s12 m5 l4">
              <input type="password" name="password" class="validate" minlength="2" maxlength="250" required value="">
              <label>Contraseña</label>
            </div>
            <div class="center-align col s12">
                <button type="submit" class="waves-effect waves-light btn blue center-align"><i class="material-icons left">save</i>Registrar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  


  

resources/views/template/partials/nav.blade.php
<!-- Dropdown Structure -->
<ul id="dropdown1" class="dropdown-content {{ $color }}">
  @auth
  <li><a href="{{ route('perfil.show',Auth::user()) }}">Ver Perfil</a></li>
  <li><a href="{{ route('perfil.edit',Auth::user()->id) }}">Editar Perfil</a></li>
  <li class="divider {{ $colorDiv }}"></li>
  <li><a href="{{ url('logout') }}"
    onclick="event.preventDefault();
    document.getElementById('logout-form').submit();
    ">Cerrar Sesión</a>
    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
      {{ csrf_field() }}
    </form>
  </li>
  @endauth
</ul>


<!-- El contenerdor del sideNav -->
  @include('template.partials.side-nav')

<div class="navbar-fixed">
  <nav class="{{ $colorPag }}">
    <div class="nav-wrapper">

      <a href="{{ url('/') }}" class="hide-on-large-only" style="font-size: 1.8rem;">{{ $tema }}</a>

      <a href="#" data-activates="side-nav-pagina" class="button-collapse"><i class="material-icons">menu</i></a>
      
      <ul class="right hide-on-med-and-down">
        @guest
        <li><a class="modal-trigger {{ $textPag }}" href="{{ route('login') }}">Iniciar sesion</a></li>
        @endguest
        @auth
        <li><a class="dropdown-button {{ $textPag }}" href="#!" data-activates="dropdown1"><div class="chip"><img src="{{ asset('img/perfil.jpg') }}" alt="Photo Profile">{{ Auth::user()->nombre.' '.Auth::user()->paterno.' '.Auth::user()->materno }}</div><i class="material-icons right">arrow_drop_down</i></a></li>
        @endauth
      </ul>

    </div>
  </nav>
</div>

resources/views/template/partials/script.blade.php
	{!! Html::script('js/jquery-3.2.1.min.js') !!}
	{!! Html::script('js/materialize.min.js') !!}
	{!! Html::script('js/jquery.validate.min.js') !!}
	{!! Html::script('js/materialize-stepper.min.js') !!}
	{!! Html::script('js/myJs.js') !!}
	{{-- 
    <script src="{{ asset('js/jquery-3.2.1.min.js') }}"></script>
    <script src="{{ asset('js/materialize.min.js') }}"></script>
	 --}}

	@yield('js')

resources/views/template/partials/side-nav.blade.php
      {{-- SideNar Para la pagina --}}

<ul class="side-nav fixed {{ $color }}" id="side-nav-pagina">
        <li><div class="user-view">
          <div class="background">
            <img class="responsive-img" src="{{ asset('img/fiis-logo.png') }}" style="height: 100%;">
          </div>
          <a href="{{ route('home') }}"><span class="black-text name"><br><br><br>{{ $tema }}</span></a>
        </div></li>
        
        {{-- Mostrar solo cuando esta modo mobil.. --}}
        @guest
        <li class="hide-on-large-only"><a class="modal-trigger {{ $textSid }}" href="{{ route('login') }}">Iniciar sesion</a></li>
        @endguest
        @auth
        <li class="hide-on-large-only no-padding">
          <ul class="collapsible collapsible-accordion">
            <li>
              <a class="{{ $textSid }}">{{ Auth::user()->nombre }}<i class="material-icons right">arrow_drop_down</i></a>
              <div class="collapsible-body {{ $color }}">
                <ul class="left-align">
                  <li><a class="{{ $textSid }}" href="{{ route('perfil.show',Auth::user()) }}">Ver Perfil</a></li>
                  <li><a class="{{ $textSid }}" href="{{ route('perfil.edit',Auth::user()->id) }}">Editar Perfil</a></li>
                  <li class="divider  {{ $colorDiv }}"></li>
                  <li><a class="{{ $textSid }}" href="{{ url('logout') }}"
                    onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();
                    ">Cerrar Sesión</a>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                      {{ csrf_field() }}
                    </form>
                  </li>
                </ul>
              </div>
            </li>
          </ul>
        </li>
        <li class="hide-on-large-only"><div class="divider {{ $colorDiv }}"></div></li>
        {{-- END.. Mostrar solo cuando esta modo mobil.. --}}

		
		{{-- SideNav del director --}}
    @if(DB::table('persona_role')
      ->join('roles','roles.id','persona_role.role_id')
      ->where('persona_role.persona_id','=',Auth::user()->id)
      ->where('roles.nombre','=','Director')
      ->first()
      )
        <li><a href="{{ route('director.semestre.index') }}" class="{{ $textSid }}">Semestres</a></li>
        <li><a href="{{ route('director.curso.index') }}" class="{{ $textSid }}">Cursos</a></li>
        <li><a href="{{ route('director.docente.index') }}" class="{{ $textSid }}">Docentes</a></li>   
        <li><a href="{{ route('director.silabo.index') }}" class="{{ $textSid }}">Silabos</a></li>        
        <li class="divider {{ $colorDiv }}"></li>
        {{-- END SideNav del director --}}
    @endif

		{{-- SideNav del Docente --}}
    @if(DB::table('persona_role')
      ->join('roles','roles.id','persona_role.role_id')
      ->where('persona_role.persona_id','=',Auth::user()->id)
      ->where('roles.nombre','=','Docente')
      ->first()
      )
        <li><a href="{{ route('docente.curso.index') }}" class="{{ $textSid }}">Mis cursos</a></li>
        <li><a href="{{ route('docente.tema.index') }}" class="{{ $textSid }}">Mis temas</a></li>      
        <li class="divider {{ $colorDiv }}"></li>
        {{-- END SideNav del Docente --}}
    @endif

		{{-- SideNav del Delegado --}}
    @if(DB::table('persona_role')
      ->join('roles','roles.id','persona_role.role_id')
      ->where('persona_role.persona_id','=',Auth::user()->id)
      ->where('roles.nombre','=','Delegado')
      ->first()
      )
        <li><a href="{{ route('delegado.curso.index')}}" class="{{ $textSid }}">Mis cursos</a></li>    
        <li class="divider {{ $colorDiv }}"></li>
        {{-- END SideNav del Delegado --}}
    @endif

        @endauth
        <li><a href="" class="{{ $textSid }}">Ayuda</a></li>
</ul>

resources/views/template/partials/style.blade.php
	{!! Html::style('css/materialize.css') !!}
	{!! Html::style('css/materialize-Icon.css') !!}
	{!! Html::style('css/materialize-stepper.css') !!}
	{!! Html::style('css/myCss.css') !!}
	{{-- 
	{!! Html::style('https://fonts.googleapis.com/icon?family=Material+Icons') !!}
	<link href="{{ asset('https://fonts.googleapis.com/icon?family=Material+Icons') }}" rel="stylesheet">
	<link type="text/css" rel="stylesheet" href="{{ asset('css/materialize.min.css') }}"  media="screen,projection"/>
	 --}}
	 @yield('css')