routes/web.php
<?php


Route::get('/', function () {
    return view('home');
});

/*Haciendo un grupo de rutas... para el Director*/
Route::group(['prefix' => 'director', 'namespace' => 'Director', 'as' =>'director.', 'middleware' => ['auth','director']], function(){
	//Grupo de rutas para el Director/Curso
	Route::group(['prefix' => 'curso', 'as' =>'curso.'], function(){
		Route::get('/', [
			'uses' => 'CursoController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'CursoController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'CursoController@store',
			'as' => 'store']);
		Route::get('{curso}',[
			'uses' => 'CursoController@show',
			'as' => 'show']);
		Route::get('{curso}/edit',[
			'uses' => 'CursoController@edit',
			'as' => 'edit']);
		Route::put('{curso}',[
			'uses' => 'CursoController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'CursoController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Director/Docente
	Route::group(['prefix' => 'docente', 'as' =>'docente.'], function(){
		Route::get('/', [
			'uses' => 'DocenteController@index',
			'as' => 'index']);
		Route::post('/',[
			'uses' => 'DocenteController@store',
			'as' => 'store']);
		Route::get('{docente}',[
			'uses' => 'DocenteController@show',
			'as' => 'show']);
		Route::get('{docente}/edit',[
			'uses' => 'DocenteController@edit',
			'as' => 'edit']);
		Route::put('{docente}',[
			'uses' => 'DocenteController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'DocenteController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Director/Semestre
	Route::group(['prefix' => 'semestre', 'as' =>'semestre.'], function(){
		Route::get('/', [
			'uses' => 'SemestreController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'SemestreController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'SemestreController@store',
			'as' => 'store']);
		Route::post('storeCurso',[
			'uses' => 'SemestreController@storeCurso',
			'as' => 'storeCurso']);
		Route::post('storeCursoDocente',[
			'uses' => 'SemestreController@storeCursoDocente',
			'as' => 'storeCursoDocente']);
		Route::get('{semestre}',[
			'uses' => 'SemestreController@show',
			'as' => 'show']);
		Route::get('{semestre}/edit',[
			'uses' => 'SemestreController@edit',
			'as' => 'edit']);
		Route::put('{semestre}',[
			'uses' => 'SemestreController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'SemestreController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Director/silabo

	Route::group(['prefix' => 'silabo', 'as' =>'silabo.'], function(){
		Route::get('/', [
			'uses' => 'SilaboController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'SilaboController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'SilaboController@store',
			'as' => 'store']);
		Route::get('{silabo}',[
			'uses' => 'SilaboController@show',
			'as' => 'show']);
		Route::get('{silabo}/edit',[
			'uses' => 'SilaboController@edit',
			'as' => 'edit']);
		Route::put('{silabo}',[
			'uses' => 'SilaboController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'SilaboController@destroy',
			'as' => 'destroy']);
		Route::get('{silabo}',[
			'uses' => 'SilaboController@temaIndex',
			'as' => 'temaIndex']);
	});

	//Route::resource('silabo', 'SilaboController');


});


/*Haciendo un grupo de rutas... para el Docente*/
Route::group(['prefix' => 'docente', 'namespace' => 'Docente', 'as' =>'docente.', 'middleware' => ['auth','docente']], function(){
	//Grupo de rutas para el Docente/curso
	Route::group(['prefix' => 'curso', 'as' =>'curso.'], function(){
		Route::get('/', [
			'uses' => 'CursoController@index',
			'as' => 'index']);
		Route::post('create', [
			'uses' => 'CursoController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'CursoController@store',
			'as' => 'store']);
		Route::get('{curso}',[
			'uses' => 'CursoController@show',
			'as' => 'show']);
		Route::get('{curso}/edit',[
			'uses' => 'CursoController@edit',
			'as' => 'edit']);
		Route::put('{curso}',[
			'uses' => 'CursoController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'CursoController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Docente/temas
	Route::group(['prefix' => 'tema', 'as' =>'tema.'], function(){
		Route::get('/', [
			'uses' => 'TemaController@index',
			'as' => 'index']);
		Route::post('/',[
			'uses' => 'TemaController@store',
			'as' => 'store']);
		Route::get('{tema}',[
			'uses' => 'TemaController@show',
			'as' => 'show']);
		Route::get('{tema}/edit',[
			'uses' => 'TemaController@edit',
			'as' => 'edit']);
		Route::put('{tema}',[
			'uses' => 'TemaController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'TemaController@destroy',
			'as' => 'destroy']);
	});	
});

/*Haciendo un grupo de rutas... para el Delegado*/
Route::group(['prefix' => 'delegado', 'namespace' => 'Delegado', 'as' =>'delegado.', 'middleware' => ['auth','delegado']], function(){
	//Grupo de rutas para el Delegado/cursos
	Route::group(['prefix' => 'curso', 'as' =>'curso.'], function(){
		Route::get('/', [
			'uses' => 'CursoController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'CursoController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'CursoController@store',
			'as' => 'store']);
		Route::get('{curso}',[
			'uses' => 'CursoController@show',
			'as' => 'show']);
		Route::get('{curso}/edit',[
			'uses' => 'CursoController@edit',
			'as' => 'edit']);
		Route::put('{curso}',[
			'uses' => 'CursoController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'CursoController@destroy',
			'as' => 'destroy']);
	});
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'perfil', 'as' => 'perfil.', 'middleware' => 'auth'], function(){
	Route::get('/', [
		'uses' => 'PersonaController@index',
		'as' => 'index']);
	Route::get('create', [
		'uses' => 'PersonaController@create',
		'as' => 'create']);
	Route::post('/',[
		'uses' => 'PersonaController@store',
		'as' => 'store']);
	Route::get('{semestre}',[
		'uses' => 'PersonaController@show',
		'as' => 'show']);
	Route::get('{semestre}/edit',[
		'uses' => 'PersonaController@edit',
		'as' => 'edit']);
	Route::put('{semestre}',[
		'uses' => 'PersonaController@update',
		'as' => 'update']);
	Route::get('{id}/destroy',[
		'uses' => 'PersonaController@destroy',
		'as' => 'destroy']);
});

app/Http/Controllers/Director/CursoController.php
<?php

namespace CSilabo\Http\Controllers\Director;

use Illuminate\Http\Request;
use CSilabo\Http\Controllers\Controller;

use CSilabo\Model\Curso;
use CSilabo\Model\curso_requisito;
use CSilabo\Model\Sumilla;
use Validator;
use DB;
class CursoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$cursos = Curso::all()->select('id','codigo','nombre')->orderBy('codigo','ASC')->get();
        $cursos=DB::table('cursos')
            ->select('id','codigo','nombre')
            ->orderBy('codigo','ASC')
            ->get();
        //dd($cursos);
        return view('director.curso.index', compact('cursos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cursos = Curso::orderBy('id','DESC')->get();
        return view('director.curso.create', compact('cursos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nombre' => 'required|min:2|max:100|unique:cursos',
            'codigo' => 'required|min:10|max:10|unique:cursos',
            /*'creditos' => 'required|min:2|max:100',
            'codigo' => 'required|numeric|min:10|max:10',
            'creditos' => 'required|numeric|min:10|max:10',*/
        ]);

        if($validator->fails()){
            flash('Informacion ya exitente')->error();
            return redirect()->route('director.curso.index')
                        ->withErrors($validator)
                        ->withInput();
        }
        $curso=new Curso($request->all());
        $curso->save();
        $sumilla=new sumilla();
        $sumilla->descripcion=$request->sumilla;
        $sumilla->estado='vigente';
        $sumilla->fecha=date('Y-m-d');
        $sumilla->curso_id=$curso->id;
        $sumilla->save();

        //$curso->curso_requisito()->sync($request->curso_requisito);
        if ($request->curso_requisito!=null) {
            foreach ($request->curso_requisito as $c_requisito) {
                $curso_requisito= new curso_requisito();
                $curso_requisito->curso_id=$curso->id;
                $curso_requisito->curso_requisito_id=$c_requisito;
                $curso_requisito->save();
            }
        }
        

        flash('Registrado correctamente')->success();
        return redirect()->route('director.curso.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $curso=Curso::find($id);
        $curso->delete();
        flash('Curso '.$curso->nombre.' Eliminado')->error();
        return redirect()->route('director.curso.index');
    }
}

app/Http/Controllers/Director/DirectorController.php
<?php

namespace CSilabo\Http\Controllers\Director;

use Illuminate\Http\Request;
use CSilabo\Http\Controllers\Controller;

class DirectorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Director/DocenteController.php
<?php

namespace CSilabo\Http\Controllers\Director;

use Illuminate\Http\Request;
use CSilabo\Http\Controllers\Controller;

use CSilabo\Model\Persona;
use CSilabo\Model\Role;
use DB;
use Validator;
class DocenteController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $docentes = DB::table('personas')
            ->join('persona_role', 'persona_role.persona_id', '=', 'personas.id')
            ->select('personas.*')
            ->where('persona_role.role_id', '=', 1)
            ->orderBy('paterno', 'ASC')
            ->get();
        return view('director.docente.index',compact('docentes'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nombre' => 'required|min:2|max:100',
            'paterno' => 'required|min:2|max:100',
            'materno' => 'max:100',
            'email' => 'email|required|unique:personas',
            'codigo' => 'nullable|unique:personas',
            'password' => 'required|min:4|max:255',
        ]);
        if($validator->fails()){
            return redirect()->route('director.docente.index')
                        ->withErrors($validator)
                        ->withInput();
        }
        $persona=new Persona($request->all());
        //$user->fill($request->all());
        $persona->password=bcrypt($request->password);
        $persona->save();

        $role=Role::where('nombre','Docente')->select('id')->get();

        $persona->roles()->sync($role);
        flash('Registrado correctamente')->success();
        return redirect()->route('director.docente.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $docente = Persona::find($id);
        return view('director.docente.show', compact('docente'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $docente = Persona::find($id);
        return view('director.docente.edit', compact('docente'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'nombre' => 'required|min:2|max:100',
            'paterno' => 'required|min:2|max:100',
            'materno' => 'required|min:2|max:100',
            'codigo' => 'nullable|unique:personas',
            'email' => 'email|required',
            'password' => 'required|min:4|max:255',
        ]);
        //dd($request->email);
        $var = DB::table('personas')
                ->where('personas.email','=',$request->email)
                ->where('personas.id','<>',$id)
                ->count();
        //dd($var);
        if($var){
            $validator->errors()->add('field', 'Email registrado a otra persona');
            flash('Email existente');
        }

        if($validator->fails() || $var){
            return redirect()->route('director.docente.index')
                        ->withErrors($validator)
                        ->withInput();
        }
        $docente=Persona::find($id);
        $docente->fill($request->all());
        $docente->password=bcrypt($request->password);
        $docente->save();
        flash('Modificado Correctamente')->success();
        return redirect()->route('director.docente.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $docente=Persona::find($id);
        $docente->delete();
        flash('Docente '.$docente->nombre.' Eliminado')->error();
        return redirect()->route('director.docente.index');
    }
}

resources/views/director/semestre/index.blade.php
@extends('template.main')

@section('title-body','SEMESTRES')
@section('content')
<div class="row">
<!-- Modal Registro de semestre -->
  <div id="semestre-edit" class="modal">
    <div class="modal-content">      
      <div class="row">
          <form class="col s12 m10 l8 offset-l2 offset-m1" method="POST" action="{{ route('director.semestre.store') }}">
            {{ csrf_field() }}
            <div class="row center-align"><h4>Registro de Semestre</h4></div>
            <div class="row">
              <div class="col s6 m2 offset-m1">
                <p class="">AÑO</p>
              </div>
              <div class="col s6 m3">
                <input type="text" name="año" id="año" class="validate" placeholder="AÑO">
              </div>
                  <div class="col s6 m2 offset-m1">
                      <p class="">NÚMERO</p>
                  </div>
                  <div class="col s6 m3">
                      <input type="text" name="numero" id="numero" class="validate" placeholder="NÚMERO">
                  </div>
            </div>

              <div class="center-align">
                  <button type="submit" class="waves-effect waves-light btn blue center-align"><i class="material-icons left">save</i>Guardar</button>
              </div>
              <br>
          </form>
        </div>
    </div>
  </div>

  

    <div class="col s12 m9 nav nav-wrapper">
      <form>
        <div class="input-field col s8">
          <input id="search" type="search" required class="validate" placeholder="[Buscar]">
        </div>
        <div class="col s2 right-align">
            <a class="btn-floating waves-effect waves-light blue darken-4"><i class="material-icons">search</i></a>
        </div>
      </form>
      <div class="col s2">
          <a class="btn-floating waves-effect waves-light green darken-4"><i class="material-icons">update</i></a>
      </div>
    </div>
    <div class="col s12 m3 right-align">
        <span>Agregar <a class="btn-floating waves-effect waves-light modal-trigger red darken-4" href="#semestre-create"><i class="material-icons">add</i></a></span>
    </div>
</div>

      <table class="highlight responsive-table">
        <thead>
          <tr>
              <th>Semestre</th>
              <th>Acciones</th>
          </tr>
        </thead>

        <tbody>
          @foreach($semestres as $semestre)
          <tr>
            <td>{{ $semestre->año.' - '.$semestre->numero }}</td>
            <td>
                <a class="btn-floating waves-effect waves-light green darken-4 modal-trigger" href="#semestre-edit"><i class="material-icons">edit</i></a>
                <a class="btn-floating waves-effect waves-light red darken-4" href="{{ route('director.semestre.destroy',$semestre->id) }}"><i class="material-icons" onclick="return confirm('Seguro que desea Eliminar?')">delete</i></a>
                <a class="btn-floating waves-effect waves-light blue darken-4" href="{{ route('director.semestre.show',$semestre->id) }}"><i class="material-icons">remove_red_eye</i></a>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>

@endsection

resources/views/director/semestre/show.blade.php
@extends('template.main')

@section('title-body',"$semestre->año - $semestre->numero")
@section('content')

  <!-- Modal Agregar curso.. -->
  <div id="semestre-show-add" class="modal">
    <div class="modal-content">      
      <div class="row">
          <form method="POST" action="{{ route('director.semestre.storeCurso') }}">
            {{ csrf_field() }}
            <input type="hidden" name="semestreId" value="{{ $semestre->id }}">
          <div class="row">

            <h5 class="center-align">Activar cursos para el semestre</h5>

            <div class="row">
                <div class="input-field col s8 offset-s2">
                    <select multiple required name="cursosActivados[]" id="curso_requisito">
                        <option value="" disabled selected>Seleccione los cursos</option>
                        @foreach($cursosdisponibles as $curso)
                          <?php
                            $selected='';
                            foreach($vector as $val){
                              if($val==$curso->id){
                                $selected='selected';
                                break;
                              }
                            }
                          ?>
                          <option value="{{ $curso->id }}" {{ $selected }}>{{ $curso->nombre }}</option>
                        @endforeach
                    </select>
                    <label>Cursos  a activar</label>
                </div>
            </div>

            <div class="center-align col s12">
                <button type="submit" class="waves-effect waves-light btn blue center-align"><i class="material-icons left">save</i>Registrar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>


  <!-- Modal Agregar Docente al curso.. -->
  <div id="semestre-show-add-docente" class="modal">
    <div class="modal-content">      
      <div class="row">
          <form method="POST" action="{{ route('director.semestre.storeCursoDocente') }}">
            {{ csrf_field() }}
            <input type="hidden" name="semestreId" value="{{ $semestre->id }}">
            <input type="hidden" name="curso_id" id="curso_id">
            <input type="hidden" name="grupo" value="I">
          <div class="row">

            <h5 class="center-align">Asignar docente al curso</h5>

            <div class="row">
                <div class="input-field col s8 offset-s2">
                    <select required name="persona_id">
                        <option value="" disabled selected>Seleccione docente</option>
                        @foreach($docentes as $docente)
                        <option value="{{ $docente->id }}">{{ $docente->nombre }}</option>
                        @endforeach
                    </select>
                    <label>Seleccione el docente del curso</label>
                </div>
            </div>

            <div class="center-align col s12">
                <button type="submit" class="waves-effect waves-light btn blue center-align"><i class="material-icons left">save</i>Registrar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>


<div class="row">

    <div class="col s12 m9 nav nav-wrapper">
      <form>
        <div class="input-field col s8">
          <input id="search" type="search" required class="validate" placeholder="[Buscar]">
        </div>
        <div class="col s2 right-align">
            <a class="btn-floating waves-effect waves-light blue darken-4"><i class="material-icons">search</i></a>
        </div>
      </form>
      <div class="col s2">
          <a class="btn-floating waves-effect waves-light green darken-4"><i class="material-icons">update</i></a>
      </div>
    </div>
    <div class="col s12 m3 right-align">
        <span>Agregar <a class="btn-floating waves-effect waves-light modal-trigger red darken-4" href="#semestre-show-add"><i class="material-icons">add</i></a></span>
    </div>
</div>

      <table class="highlight responsive-table">
        <thead>
          <tr>
              <th>Codugo</th>
              <th>Nombre</th>
              <th colspan="2">Docente(s)</th>
          </tr>
        </thead>

        <tbody>
          @foreach($semestre->cursos as $curso)
          <tr>
            <td>{{ $curso->codigo }}</td>
            <td>{{ $curso->nombre }}</td>
            <td>
              <?php
              $docentes=DB::table('curso_activado')
                ->join('curso_docente','curso_docente.curso_id','=','curso_activado.id')
                ->join('personas','personas.id','=','curso_docente.persona_id')
                ->selectRaw("CONCAT(personas.nombre,' ',personas.paterno,'.') as nombre")
                ->where('curso_activado.curso_id','=',$curso->id)
                ->where('curso_activado.semestre_id','=',$semestre->id)
                ->get();
                //dd($docentes);
              ?>
              @foreach($docentes as $cActivado)
                <p>{{ $cActivado->nombre }}</p>
              @endforeach
            </td>
            <td>              
                <a class="btn-floating waves-effect waves-light modal-trigger blue darken-4" href="#semestre-show-add-docente" onclick="cambiaDefecto({{ $curso->id }})"><i class="material-icons">person_add</i></a>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>

  <script> 
    function cambiaDefecto(valor){ 
        document.getElementById("curso_id").value=valor;
    }
  </script> 
@endsection