routes/web.php
<?php


Route::get('/', function () {
    return view('home');
});

/*Haciendo un grupo de rutas... para el Director*/
Route::group(['prefix' => 'director', 'namespace' => 'Director', 'as' =>'director.', 'middleware' => ['auth','director']], function(){
	//Grupo de rutas para el Director/Curso
	Route::group(['prefix' => 'curso', 'as' =>'curso.'], function(){
		Route::get('/', [
			'uses' => 'CursoController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'CursoController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'CursoController@store',
			'as' => 'store']);
		Route::get('{curso}',[
			'uses' => 'CursoController@show',
			'as' => 'show']);
		Route::get('{curso}/edit',[
			'uses' => 'CursoController@edit',
			'as' => 'edit']);
		Route::put('{curso}',[
			'uses' => 'CursoController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'CursoController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Director/Docente
	Route::group(['prefix' => 'docente', 'as' =>'docente.'], function(){
		Route::get('/', [
			'uses' => 'DocenteController@index',
			'as' => 'index']);
		Route::post('/',[
			'uses' => 'DocenteController@store',
			'as' => 'store']);
		Route::get('{docente}',[
			'uses' => 'DocenteController@show',
			'as' => 'show']);
		Route::get('{docente}/edit',[
			'uses' => 'DocenteController@edit',
			'as' => 'edit']);
		Route::put('{docente}',[
			'uses' => 'DocenteController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'DocenteController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Director/Semestre
	Route::group(['prefix' => 'semestre', 'as' =>'semestre.'], function(){
		Route::get('/', [
			'uses' => 'SemestreController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'SemestreController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'SemestreController@store',
			'as' => 'store']);
		Route::post('storeCurso',[
			'uses' => 'SemestreController@storeCurso',
			'as' => 'storeCurso']);
		Route::post('storeCursoDocente',[
			'uses' => 'SemestreController@storeCursoDocente',
			'as' => 'storeCursoDocente']);
		Route::get('{semestre}',[
			'uses' => 'SemestreController@show',
			'as' => 'show']);
		Route::get('{semestre}/edit',[
			'uses' => 'SemestreController@edit',
			'as' => 'edit']);
		Route::put('{semestre}',[
			'uses' => 'SemestreController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'SemestreController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Director/silabo

	Route::group(['prefix' => 'silabo', 'as' =>'silabo.'], function(){
		Route::get('/', [
			'uses' => 'SilaboController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'SilaboController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'SilaboController@store',
			'as' => 'store']);
		Route::get('{silabo}',[
			'uses' => 'SilaboController@show',
			'as' => 'show']);
		Route::get('{silabo}/edit',[
			'uses' => 'SilaboController@edit',
			'as' => 'edit']);
		Route::put('{silabo}',[
			'uses' => 'SilaboController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'SilaboController@destroy',
			'as' => 'destroy']);
		Route::get('{silabo}',[
			'uses' => 'SilaboController@temaIndex',
			'as' => 'temaIndex']);
	});

	//Route::resource('silabo', 'SilaboController');


});


/*Haciendo un grupo de rutas... para el Docente*/
Route::group(['prefix' => 'docente', 'namespace' => 'Docente', 'as' =>'docente.', 'middleware' => ['auth','docente']], function(){
	//Grupo de rutas para el Docente/curso
	Route::group(['prefix' => 'curso', 'as' =>'curso.'], function(){
		Route::get('/', [
			'uses' => 'CursoController@index',
			'as' => 'index']);
		Route::post('create', [
			'uses' => 'CursoController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'CursoController@store',
			'as' => 'store']);
		Route::get('{curso}',[
			'uses' => 'CursoController@show',
			'as' => 'show']);
		Route::get('{curso}/edit',[
			'uses' => 'CursoController@edit',
			'as' => 'edit']);
		Route::put('{curso}',[
			'uses' => 'CursoController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'CursoController@destroy',
			'as' => 'destroy']);
	});
	//Grupo de rutas para el Docente/temas
	Route::group(['prefix' => 'tema', 'as' =>'tema.'], function(){
		Route::get('/', [
			'uses' => 'TemaController@index',
			'as' => 'index']);
		Route::post('/',[
			'uses' => 'TemaController@store',
			'as' => 'store']);
		Route::get('{tema}',[
			'uses' => 'TemaController@show',
			'as' => 'show']);
		Route::get('{tema}/edit',[
			'uses' => 'TemaController@edit',
			'as' => 'edit']);
		Route::put('{tema}',[
			'uses' => 'TemaController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'TemaController@destroy',
			'as' => 'destroy']);
	});	
});

/*Haciendo un grupo de rutas... para el Delegado*/
Route::group(['prefix' => 'delegado', 'namespace' => 'Delegado', 'as' =>'delegado.', 'middleware' => ['auth','delegado']], function(){
	//Grupo de rutas para el Delegado/cursos
	Route::group(['prefix' => 'curso', 'as' =>'curso.'], function(){
		Route::get('/', [
			'uses' => 'CursoController@index',
			'as' => 'index']);
		Route::get('create', [
			'uses' => 'CursoController@create',
			'as' => 'create']);
		Route::post('/',[
			'uses' => 'CursoController@store',
			'as' => 'store']);
		Route::get('{curso}',[
			'uses' => 'CursoController@show',
			'as' => 'show']);
		Route::get('{curso}/edit',[
			'uses' => 'CursoController@edit',
			'as' => 'edit']);
		Route::put('{curso}',[
			'uses' => 'CursoController@update',
			'as' => 'update']);
		Route::get('{id}/destroy',[
			'uses' => 'CursoController@destroy',
			'as' => 'destroy']);
	});
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'perfil', 'as' => 'perfil.', 'middleware' => 'auth'], function(){
	Route::get('/', [
		'uses' => 'PersonaController@index',
		'as' => 'index']);
	Route::get('create', [
		'uses' => 'PersonaController@create',
		'as' => 'create']);
	Route::post('/',[
		'uses' => 'PersonaController@store',
		'as' => 'store']);
	Route::get('{semestre}',[
		'uses' => 'PersonaController@show',
		'as' => 'show']);
	Route::get('{semestre}/edit',[
		'uses' => 'PersonaController@edit',
		'as' => 'edit']);
	Route::put('{semestre}',[
		'uses' => 'PersonaController@update',
		'as' => 'update']);
	Route::get('{id}/destroy',[
		'uses' => 'PersonaController@destroy',
		'as' => 'destroy']);
});

app/Http/Controllers/Delegado/CursoController.php
<?php

namespace CSilabo\Http\Controllers\Delegado;

use Illuminate\Http\Request;
use CSilabo\Http\Controllers\Controller;

class CursoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('delegado.curso.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Director/CursoController.php
<?php

namespace CSilabo\Http\Controllers\Director;

use Illuminate\Http\Request;
use CSilabo\Http\Controllers\Controller;

use CSilabo\Model\Curso;
use CSilabo\Model\curso_requisito;
use CSilabo\Model\Sumilla;
use Validator;
use DB;
class CursoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //$cursos = Curso::all()->select('id','codigo','nombre')->orderBy('codigo','ASC')->get();
        $cursos=DB::table('cursos')
            ->select('id','codigo','nombre')
            ->orderBy('codigo','ASC')
            ->get();
        //dd($cursos);
        return view('director.curso.index', compact('cursos'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cursos = Curso::orderBy('id','DESC')->get();
        return view('director.curso.create', compact('cursos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'nombre' => 'required|min:2|max:100|unique:cursos',
            'codigo' => 'required|min:10|max:10|unique:cursos',
            /*'creditos' => 'required|min:2|max:100',
            'codigo' => 'required|numeric|min:10|max:10',
            'creditos' => 'required|numeric|min:10|max:10',*/
        ]);

        if($validator->fails()){
            flash('Informacion ya exitente')->error();
            return redirect()->route('director.curso.index')
                        ->withErrors($validator)
                        ->withInput();
        }
        $curso=new Curso($request->all());
        $curso->save();
        $sumilla=new sumilla();
        $sumilla->descripcion=$request->sumilla;
        $sumilla->estado='vigente';
        $sumilla->fecha=date('Y-m-d');
        $sumilla->curso_id=$curso->id;
        $sumilla->save();

        //$curso->curso_requisito()->sync($request->curso_requisito);
        if ($request->curso_requisito!=null) {
            foreach ($request->curso_requisito as $c_requisito) {
                $curso_requisito= new curso_requisito();
                $curso_requisito->curso_id=$curso->id;
                $curso_requisito->curso_requisito_id=$c_requisito;
                $curso_requisito->save();
            }
        }
        

        flash('Registrado correctamente')->success();
        return redirect()->route('director.curso.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $curso=Curso::find($id);
        $curso->delete();
        flash('Curso '.$curso->nombre.' Eliminado')->error();
        return redirect()->route('director.curso.index');
    }
}

app/Http/Controllers/Director/DirectorController.php
<?php

namespace CSilabo\Http\Controllers\Director;

use Illuminate\Http\Request;
use CSilabo\Http\Controllers\Controller;

class DirectorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Director/HomeController.php
<?php

namespace CSilabo\Http\Controllers\Director;

use Illuminate\Http\Request;
use CSilabo\Http\Controllers\Controller;

class HomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Director/SilaboController.php
<?php

namespace CSilabo\Http\Controllers\Director;

use Illuminate\Http\Request;
use CSilabo\Http\Controllers\Controller;
use DB;
class SilaboController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $silabos1=DB::table('t_silabos')->get();
        return view('director.silabo.index',compact('silabos1'));
    }

    public function temaIndex(Request $request){
      return view('director.silabo.temaIndex',compact('id'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/director/curso/create.blade.php
@extends('template.main')

@section('title-body','CURSO')
@section('content')
<div class="row">
    <form class="col s12 m10 offset-m1" method="POST" action="{{ route('director.curso.store') }}">
            {{ csrf_field() }}
    	<div class="row">
    		<h5 class="center-align">Registro de creación de curso</h5>
    	</div>

        <div class="row">
            <div class="input-field col s12">
                <input id="nombre" name="nombre" type="text" class="validate" required minlength="2" maxlength="100" data-length="100">
                <label for="silabo_name">Nombre del curso</label>
            </div>
        </div>

        <div class="row">
            <div class="col s5 m3">
                <p class="">Codigo</p>
            </div>
            <div class="col s7 m3">
                <input type="text" name="codigo" id="codigo" class="validate" placeholder="Codigo" required data-length="10" minlength="2" maxlength="10">
            </div>
            <div class="col s5 m3">
                <p class="">Creditos</p>
            </div>
            <div class="col s7 m3">
                <input type="text" name="creditos" id="creditos" class="validate" placeholder="Creditos" required>
            </div>
        </div>

        <div class="row">
            <div class="col s4 m3">
                <p class="">Horas Teoricas</p>
            </div>
            <div class="col s2 m3">
                <input type="text" name="hora_teorica" id="hora_teorica" class="validate" placeholder="Horas Teoricas" required>
            </div>
            <div class="col s4 m3">
                <p class="">Horas prácticas</p>
            </div>
            <div class="col s2 m3">
                <input type="text" name="hora_practica" id="hora_practica" class="validate" placeholder="Horas prácticas" required>
            </div>
        </div>

        <div class="row">
            <div class="col s12">
                <p class="">Sumilla</p>
            </div>
            <div class="col s11 offset-s1">
                <textarea id=sumilla"" name="sumilla" class="materialize-textarea validate" placeholder="Sumilla del curso" required></textarea>
            </div>
        </div>

        <div class="row">
            <div class="col s5 m2">
                <p class="">Ciclo</p>
            </div>
            <div class="input-field col s7 m2">
                <select required name="ciclo" id="ciclo">
                    <option value="" disabled selected>...</option>
                    <option value="I">I</option>
                    <option value="II">II</option>
                    <option value="III">III</option>
                    <option value="IV">IV</option>
                    <option value="V">V</option>
                    <option value="VI">VI</option>
                    <option value="VII">VII</option>
                    <option value="VIII">VIII</option>
                    <option value="IX">IX</option>
                    <option value="X">X</option>
                </select>
            </div>
            <div class="col s5 m2 offset-m1">
                <p class="">Caracter</p>
            </div>
            <div class="input-field col s7 m5">
                <select required name="caracter" id="caracter">
                    <option value="" disabled selected>Seleccione una opcion</option>
                    <option value="Obligatorio">Obligatorio</option>
                    <option value="Electivo">Electivo</option>
                </select>
            </div>
        </div>

        <div class="row">
            <div class="col s5">
                <p class="">Área</p>
            </div>
            <div class="input-field col s7">
                <select required name="area" id="area">
                    <option value="" disabled selected>Seleccione el area</option>
                    <option value="Departamento Academico de Ciencia en Informatica y Sistemas.">DACIS</option>
                    <option value="Ciencias basicas.">Ciencias Basicas</option>
                </select>
            </div>
        </div>

        <div class="row">
            <div class="col s5">
                <p class="">Curso requisito(s)</p>
            </div>
            <div class="input-field col s7">
                <select multiple required name="curso_requisito[]" id="curso_requisito">
                    <option value="" disabled selected>Seleccione los cursos</option>
                    @foreach($cursos as $curso)
                    <option value="{{ $curso->id }}">{{ $curso->nombre }}</option>
                    @endforeach
                </select>
            </div>
        </div>

        <div class="center-align">
            <button type="submit" class="waves-effect waves-light btn blue center-align"><i class="material-icons left">save</i>Guardar</button>
        </div>
        <br>
    </form>
  </div>

@endsection

resources/views/director/curso/index.blade.php
@extends('template.main')

@section('title-body','CURSOS')
@section('content')

<div class="row">

    <div class="col s12 m9 nav nav-wrapper">
      <form>
        <div class="input-field col s8">
          <input id="search" type="search" required class="validate" placeholder="[Buscar]">
        </div>
        <div class="col s2 right-align">
            <a class="btn-floating waves-effect waves-light blue darken-4"><i class="material-icons">search</i></a>
        </div>
      </form>
      <div class="col s2">
          <a class="btn-floating waves-effect waves-light green darken-4" href="{{ route('director.curso.index') }}"><i class="material-icons">update</i></a>
      </div>
    </div>
    <div class="col s12 m3 right-align">
        <span>Agregar <a class="btn-floating waves-effect waves-light red darken-4" href="{{ route('director.curso.create') }}"><i class="material-icons">add</i></a></span>
    </div>
</div>

      <table class="highlight responsive-table">
        <thead>
          <tr>
              <th>Codigo</th>
              <th>Nombre del curso</th>
              <th>Acciones</th>
          </tr>
        </thead>

        <tbody>
          @foreach($cursos as $curso)
          <tr>
            <td>{{ $curso->codigo }}</td>
            <td>{{ $curso->nombre }}</td>
            <td>
                <a class="btn-floating waves-effect waves-light green darken-4" href="{{ route('director.curso.edit',$curso->id) }}"><i class="material-icons">edit</i></a>
                <a class="btn-floating waves-effect waves-light red darken-4" href="{{ route('director.curso.destroy',$curso->id) }}" onclick="return confirm('Seguro que desea Eliminar?')"><i class="material-icons">delete</i></a>
                <a class="btn-floating waves-effect waves-light blue darken-4" href="{{ route('director.curso.show',$curso->id) }}"><i class="material-icons">remove_red_eye</i></a>
            </td>
          </tr>
          @endforeach
        </tbody>
      </table>

@endsection